Merge Sort Algorithm
forum2k-smit/DSA-OPEN-SOURCE pull request #43
Opened 2021-10-05 19:31 UTC by rishabh99-rc

Added Merge Sort Algo via c++.

2021-10-05 19:56 UTC, rishabh-live requested changes
Write a little bit of documentation so that it is clear for begineers

2021-10-06 06:25 UTC, rishabh99-rc commented
> Write a little bit of documentation so that it is clear for beginners.

yeah, sure will do that.

2021-10-06 09:30 UTC, rishabh99-rc commented
@rishabh-live, I have made the required changes. 

I have even added the code for java & python, in case of any change do let me know, else you can pull it now.

2021-10-06 17:04 UTC, rishabh-live approved these changes

2021-10-06 17:04 UTC, merged